#! /usr/bin/env python
#include <ros/ros.h>
#include <sensor_msgs/Joy.h>

import rospy 
from sensor_msgs.msg import Joy 
from std_msgs.msg import String



def callback(data):
	msg = String()

	x0 = float(data.axes[1])
	y0 = float(data.axes[0])

	x = 50*x0+50
	y = 50*y0+50

	pub.publish(str(x))
	pub.publish(str(y))
	

	

def start():
	
	global pub
	

	pub = rospy.Publisher("joystick_reader", String ,queue_size=10)
	#subscribed to joystick input on topic Joy

	rospy.Subscriber('/joy', Joy, callback)

	rospy.init_node('joystick_reader')
	
	rate = rospy.Rate(10)
	rospy.spin()

if __name__ == '__main__':
	start()
