#! /usr/bin/env python
#include <ros/ros.h>
#include <sensor_msgs/Joy.h>

import rospy 
from std_msgs.msg import String 


def callback(data):
	rospy.loginfo(rospy.get_caller_id() + "this is %," data.data)

def talker():

	rospy.init_node('joystick_reader')
	publisher = rospy.Publisher("/joystick_data", String, queue_size=10)
	
	subscriber = rospy.Subscriber('/joy_node_data', String, callback)

	rate = rospy.Rate(10)
	
	while not rospy.is_shutdown():
	
		publisher.publish(subscriber)

		rate.sleep()
	rospy.spin

if __name__ == '__main__':
	talker()
